### PR TITLE
[master] Minor messaging improvements

### PR DESCRIPTION
**Pull request by Riva-Tholoor-Philip**
Added minor messaging improvements.

### CODE REVIEW

**Comment by rfelcman** [comment]
Sorry but not all tests passing. Please check test outputs and fix provided code.

**Comment by Riva-Tholoor-Philip** [comment]
> Sorry but not all tests passing. Please check test outputs and fix provided code.

Hi Radek,
I made necessary changes

**Comment by Riva-Tholoor-Philip** [comment]
@rfelcman  - The build looks good.

**Comment by Riva-Tholoor-Philip** [comment]
@rfelcman  , @lukasj  - The test failures has been resolved and it is ready. Please review and confirm whether we can merge it

**Review by rfelcman — APPROVED** [review]
LGTM

**Comment by Riva-Tholoor-Philip** [comment]
Thanks @rfelcman

**Pull request merged**
