### PR TITLE
[2.7] Update to use ASM 9

### PR DESCRIPTION
**Pull request by jgrassel**
Update Eclipselink to use ASM 9 (CQ 22750).

### CODE REVIEW

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
just wait for tests, please

**Review by lukasj — COMMENTED** [review]
project readme.html - the one in the repository root - should be updated too

**Comment by jgrassel** [comment]
> project readme.html - the one in the repository root - should be updated too

Thanks for catching that.  Still waiting for the CQ approval, will push an update for this file soon.

**Comment by jgrassel** [comment]
> project readme.html - the one in the repository root - should be updated too

Did you mean `about.html`?  I didn't see asm mentioned in the `readme.html`.

**Comment by jgrassel** [comment]
CQ has been approved.

**Pull request merged**
