### PR TITLE
[master] Bug 534001: Update bundle MANIFESTS for OSGI 4.3 deprecation of Requi…

### PR DESCRIPTION
**Pull request by dazey3**
for #186

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
Hmm, all the builds failed due to an invalid OSGI header. I neglected to see that we are still running with OSGI 4.1

**Comment by dazey3** [comment]
Interesting... 
According to https://www.infoq.com/news/2011/03/osgi-43:

```
// Old way
// Bundle-RequiredExecutionEnvironment: JavaSE-1.6

// New way
Require-Capability: osgi.ee;filter:="(&(osgi.ee="JavaSE")(version>=1.6))"
```

However, tycho doesnt like that new format. The issue seems to have been the quotes around `JavaSE`. I ran with:

```Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version>=1.8))"``` and all seems fine now.

**Comment by dazey3** [comment]
Also, why does `eclipselink.runtime\plugins\osgi.cmpn_4.1.0.jar` & `eclipselink.runtime\plugins\osgi.core.zip` exist? EclipseLink build process has too many points of entry -_-

**Comment by lukasj** [comment]
osgi*jar files in plugins are very likely useless these days and probably can be deleted. Let's try to deal with that within #177

**Pull request merged**
