### PR TITLE
Bug 425150 - SchemaManager.checkTableExists optimized

### PR DESCRIPTION
**Pull request by Tomas-Kraus**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=425150

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=425150

**Comment by dazey3** [comment]
@lukasj I believe this causes a regression on 2.7.2... 
You can reproduce the failure quite easily with a simple JSE test. Turn on "drop-and-create" and you can see EclipseLink is now issuing a CREATE TABLE SEQUENCE query that fails with `SQLTransactionRollbackException: Table/View 'SEQUENCE' already exists in Schema 'NA'.`

2.7.1 trace:

    [EL Finest]: query: 2018-06-29 14:55:30.459--ServerSession(-1060726397)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="DROP TABLE Inject_Ent_A")
    [EL Finest]: connection: 2018-06-29 14:55:30.461--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:55:30.461--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--DROP TABLE Inject_Ent_A
    [EL Finest]: connection: 2018-06-29 14:55:30.489--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection released to connection pool [default].
    [EL Finest]: query: 2018-06-29 14:55:30.49--ServerSession(-1060726397)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="CREATE TABLE Inject_Ent_A (ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID))")
    [EL Finest]: connection: 2018-06-29 14:55:30.49--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:55:30.49--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--CREATE TABLE Inject_Ent_A (ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID))
    [EL Finest]: connection: 2018-06-29 14:55:30.507--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection released to connection pool [default].
    [EL Finest]: ddl: 2018-06-29 14:55:30.507--Thread(Thread[main,5,main])--The table (Inject_Ent_A) is created.
    [EL Finest]: query: 2018-06-29 14:55:30.52--ServerSession(-1060726397)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'")
    [EL Finest]: connection: 2018-06-29 14:55:30.521--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:55:30.521--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
    [EL Finest]: connection: 2018-06-29 14:55:30.523--ServerSession(-1060726397)--Connection(892853636)--Thread(Thread[main,5,main])--Connection released to connection pool [default].

2.7.2 trace:

    [EL Finest]: query: 2018-06-29 14:54:51.634--ServerSession(532836669)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="DROP TABLE Inject_Ent_A")
    [EL Finest]: connection: 2018-06-29 14:54:51.634--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:54:51.635--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--DROP TABLE Inject_Ent_A
    [EL Finest]: connection: 2018-06-29 14:54:51.662--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection released to connection pool [default].
    [EL Finest]: query: 2018-06-29 14:54:51.663--ServerSession(532836669)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="CREATE TABLE Inject_Ent_A (ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID))")
    [EL Finest]: connection: 2018-06-29 14:54:51.663--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:54:51.663--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--CREATE TABLE Inject_Ent_A (ID BIGINT NOT NULL, STRDATA VARCHAR(255), PRIMARY KEY (ID))
    [EL Finest]: connection: 2018-06-29 14:54:51.681--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection released to connection pool [default].
    [EL Finest]: ddl: 2018-06-29 14:54:51.681--Thread(Thread[main,5,main])--The table (Inject_Ent_A) is created.
    [EL Finest]: query: 2018-06-29 14:54:51.693--ServerSession(532836669)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))")
    [EL Finest]: connection: 2018-06-29 14:54:51.693--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:54:51.693--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
    [EL Fine]: sql: 2018-06-29 14:54:51.724--ServerSession(532836669)--Thread(Thread[main,5,main])--VALUES(1)
    [EL Finest]: connection: 2018-06-29 14:54:51.726--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection released to connection pool [default].
    [EL Warning]: 2018-06-29 14:54:51.726--ServerSession(532836669)--Thread(Thread[main,5,main])--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.2.qualifier): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: java.sql.SQLTransactionRollbackException: Table/View 'SEQUENCE' already exists in Schema 'NA'.
        Error Code: 30000
        Call: CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
        Query: DataModifyQuery(sql="CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))")
    [EL Finest]: query: 2018-06-29 14:54:51.729--ServerSession(532836669)--Thread(Thread[main,5,main])--Execute query DataModifyQuery(sql="DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'")
    [EL Finest]: connection: 2018-06-29 14:54:51.729--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection acquired from connection pool [default].
    [EL Fine]: sql: 2018-06-29 14:54:51.729--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
    [EL Finest]: connection: 2018-06-29 14:54:51.73--ServerSession(532836669)--Connection(-526350956)--Thread(Thread[main,5,main])--Connection released to connection pool [default].```

I traced the difference in behavior to https://github.com/eclipse-ee4j/eclipselink/blob/43b93975ee5349a42e3ff92cfc6c09fa6e73e454/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/SchemaManager.java#L329

On 2.7.1, this is returning true (which is correct) but on 2.7.2 this is returning false (which is wrong since the SEQUENCE does exist...)

thoughts?

**Comment by dazey3** [comment]
@Tomas-Kraus I do think the code change is fine with moving the code to DatabasePlatform, but I think the original strategy of 

``` 
try {
    session.setLoggingOff(true);
    session.executeQuery(query);
    return true;
} catch (Exception notFound) {
    return false;
}
```

was sufficient to detect the table exists, right? My thought is that we could just use the query: 
```final String sql = "SELECT " + column + " FROM " + table.getFullName(); ```
and reuse the same "return true unless exception" logic. Thoughts?

**Comment by Tomas-Kraus** [comment]
@dazey3: Created new PR 179.
I restored my original idea of having all the code in platform to allow each platform to optimize it. The only thing I don't like here is that for MySQL/Oracle platform#checkTableExists(...) is just copy paste in both of them. But that's life. I see no nice way of extracting this code somewhere else.
I have to write some simple test to make sure that this won't get broken again.

**Pull request merged**
