### PR TITLE
add @Provider annotation to simplify auto-registration

### PR DESCRIPTION
**Pull request by slavb18**

### CODE REVIEW

**Comment by rfelcman** [comment]
Hello,

  could You please describe context, which leads into this change? By JAX-RS specification `@Provider` is not mandatory. Is it there trouble with JAX-RS implementation (Jersey, RESTEasy, Apache CXF) and discovery of this provider?

Thank You

**Comment by slavb18** [comment]
Yes, apache cxf auto discovery 
https://github.com/apache/cxf/blob/master/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/spring/AbstractSpringComponentScanServer.java

loads only @Provider annotated beans 

"JAX-RS root resources and providers annotated with JAX-RS @Path and @Provider and native CXF Providers annotated with CXF @Provider can be auto-discovered."

https://cxf.apache.org/docs/springboot.html

**Comment by slavb18** [comment]
done
1) signed ECA
2) signed and pushed commit

**Comment by rfelcman** [comment]
Sorry, GPG sign is great, but @lukasj metioned just text/comment into commit message see for example https://github.com/eclipse-ee4j/eclipselink/pull/446/commits/1c89090daf9639a51987619e15e002591f6c0b95
e-mail address must match with eclipsefdn/eca registration.

**Comment by slavb18** [comment]
added Signed-off-by

**Comment by rfelcman** [comment]
Sorry, just last bureaucracy step. Please update copyright year in the file header (line #2) into 2019 like 

`* Copyright (c) 2012, 2019 Oracle and/or its affiliates. All rights reserved.`

**Comment by slavb18** [comment]
updated copyright year in the file header

**Pull request merged**
