### PR TITLE
[2.7] ASM version switch to 9.5 to be ready for JDK 21.

### PR DESCRIPTION
**Pull request by rfelcman**
As https://central.sonatype.com/artifact/org.eclipse.persistence/org.eclipse.persistence.asm/9.5.0 is released.

### CODE REVIEW

**Review by lukasj — COMMENTED** [review]
LGTM

**Comment by rfelcman** [comment]
> I'd love to see a release! smile

See
https://github.com/eclipse-ee4j/eclipselink/releases/tag/2.7.13-RC1
https://eclipse.dev/eclipselink/downloads/milestones.php (2.7.13 section with RC1)
and Maven Central for 2.7.13-RC1 (in progress will there during 2 hours)

If everything goes well will final version will be on Thursday 27-Aug-2023.

**Comment by bmarwell** [comment]
@rfelcman I can confirm it's working on two of my projects. Thanks!

**Comment by rfelcman** [comment]
FYI: Final 2.7.13 is out

**Pull request merged**
