### PR TITLE
[2.6] Bug544192 : Index error in ForeignReferenceMapping

### PR DESCRIPTION
**Pull request by lananda**
Signed-off-by: Lalitha Ananda <lalitha.ananda@oracle.com>

### CODE REVIEW

**Comment by dazey3** [comment]
@lananda Thank you for taking the time to create a PR to fix the issue reported in 544192! Can you please update your PR to include a test that reproduces the error?

Look in the project `jpa\eclipselink.jpa.test.jse` as a location to place your test. Look at other tests in that project and model your new test in the same way. If you have any question, don't hesitate to ask.

**Comment by lananda** [comment]
> jpa



> jpa

Seems like Radek has already addressed this for a different bug 
https://github.com/eclipse-ee4j/eclipselink/pull/1426

**Comment by dazey3** [comment]
@lananda Are you looking to have #1426 backported to the EclipseLink 2.6 release? As far as I know, EclipseLink is not creating releases for that version anymore

**Comment by lukasj** [comment]
while no releases from 2.6 are not created (or at least not regularly), TopLink still needs to maintain some changes in this codebase

**Comment by lananda** [comment]
I will close this pull request and backport https://github.com/eclipse-ee4j/eclipselink/pull/1426 to 2.6 as required for this current BUG544192

**Pull request closed without merging**
