### PR TITLE
[3.0] Oracle 23 platform - backport from master

### PR DESCRIPTION
**Pull request by ajaypaul-ibm**
[3.0] Oracle 23 platform - backport from master

### CODE REVIEW

**Comment by ajaypaul-ibm** [comment]
@lukasj @rfelcman Can you please review this PR ? Thanks !

**Review by rfelcman — COMMENTED** [review]
Missing test fix for `PLSQLTest` and `XMLPLSQLTest` see attached test report for `mvn clean verify -pl :org.eclipse.persistence.jpa.test -P test-jpa-lrg,oracle` .
Note: There is different test structure, than in the master branch.
[jpa_failsafe-report.zip](https://github.com/user-attachments/files/16064626/jpa_failsafe-report.zip)

**Review by rfelcman — COMMENTED** [review]
See origin PR https://github.com/eclipse-ee4j/eclipselink/pull/1876/files#diff-8b077a4c6c50e64e7a3a7fbc3d672f940e70394519b94867b47f11fc4f495f41

**Comment by ajaypaul-ibm** [comment]
@rfelcman For XMLPLSQLTest I could only see the change of year in Copyright header . Is that only needed ?

**Comment by rfelcman** [comment]
> @rfelcman For XMLPLSQLTest I could only see the change of year in Copyright header . Is that only needed ?

Sorry no just `PLSQLTest`.

**Comment by ajaypaul-ibm** [comment]
@rfelcman When updating the oracle jdbc version in  pom.xml with 23.4.0.24.05 , build is failing . Is there anything else we have to do ?

**Comment by rfelcman** [comment]
> @rfelcman When updating the oracle jdbc version in pom.xml with 23.4.0.24.05 , build is failing . Is there anything else we have to do ?

OK so please use there `23.3.0.23.09` version like `master` https://github.com/eclipse-ee4j/eclipselink/blob/master/pom.xml#L254
I have to investigate changes in OJDBC 23.4.0.24.05 .

**Review by rfelcman — COMMENTED** [review]
LGTM

**Pull request merged**
