### PR TITLE
[Master] Add doPriv blocks to use of protected ThreadMXBean methods in ConcurrencyUtil

### PR DESCRIPTION
**Pull request by jgrassel**
Addresses the doPriv() issues as commented in #972.

### CODE REVIEW

**Review by rfelcman — APPROVED** [review]
LGTM Yes this one is better for a future usage.

**Comment by jgrassel** [comment]
@rfelcman is delivering to master sufficient, or should I also deliver this to the 3.0.0-RC1-RELEASE and/or 3.0.0-M2-RELEASE branch?

**Comment by lukasj** [comment]
I've just merged rc1 branch to master, so master is enough.

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
