### PR TITLE
[master] Bug 547056: JSE test cleanup

### PR DESCRIPTION
**Pull request by dazey3**
for #454 

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by rfelcman** [comment]
I checked these changes in "Mavenized" version with following results:
MySQL - OK
Oracle 12c - OK
Apache Derby - InMemory mode errors
```
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.111 s <<< FAILURE! - in org.eclipse.persistence.jpa.test.query.TestQueryHints
[ERROR] testJDBCQueryTimeout(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.041 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: org.apache.derby.client.am.SqlException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)

[ERROR] testMultipleNamedQueryWithScrollableCursor(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.004 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: org.apache.derby.client.am.SqlException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)

[ERROR] testQueryTimeoutUnitMinutes(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.045 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitMinutes(TestQueryHints.java:179)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitMinutes(TestQueryHints.java:179)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitMinutes(TestQueryHints.java:179)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitMinutes(TestQueryHints.java:179)
Caused by: org.apache.derby.client.am.SqlException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitMinutes(TestQueryHints.java:179)

[ERROR] testQueryTimeoutUnitSeconds(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.005 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitSeconds(TestQueryHints.java:132)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitSeconds(TestQueryHints.java:132)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitSeconds(TestQueryHints.java:132)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitSeconds(TestQueryHints.java:132)
Caused by: org.apache.derby.client.am.SqlException: Table/View 'OEPJTBMEMPLOYEE' does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testQueryTimeoutUnitSeconds(TestQueryHints.java:132)
....
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.053 s <<< FAILURE! - in org.eclipse.persistence.jpa.test.query.TestQueryProperties
[ERROR] testTimeoutUnitMinutes(org.eclipse.persistence.jpa.test.query.TestQueryProperties)  Time elapsed: 0.001 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: org.apache.derby.client.am.SqlException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)

[ERROR] testTimeoutUnitDefault(org.eclipse.persistence.jpa.test.query.TestQueryProperties)  Time elapsed: 0.02 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitDefault(TestQueryProperties.java:77)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitDefault(TestQueryProperties.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitDefault(TestQueryProperties.java:77)
Caused by: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitDefault(TestQueryProperties.java:77)
Caused by: org.apache.derby.client.am.SqlException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitDefault(TestQueryProperties.java:77)

[ERROR] testTimeoutUnitSeconds(org.eclipse.persistence.jpa.test.query.TestQueryProperties)  Time elapsed: 0.024 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitSeconds(TestQueryProperties.java:106)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitSeconds(TestQueryProperties.java:106)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitSeconds(TestQueryProperties.java:106)
Caused by: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitSeconds(TestQueryProperties.java:106)
Caused by: org.apache.derby.client.am.SqlException: 'DROP TABLE' cannot be performed on 'OEPJTBMEMPLOYEE' because it does not exist.
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitSeconds(TestQueryProperties.java:106)
```
Execution order (all DBs):
```[INFO] Running org.eclipse.persistence.jpa.converter.TestAutoApplyConverter
[INFO] Running org.eclipse.persistence.jpa.collection.TestEmbeddableKey
[INFO] Running org.eclipse.persistence.jpa.collection.TestCollectionOperations
[INFO] Running org.eclipse.persistence.jpa.compositeid.TestCompositeId
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryHints
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryProperties
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryCase
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDBPlatformDetector
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDDLGenLineTerminator
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestSchemaGen
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDBPlatformHelper
[INFO] Running org.eclipse.persistence.jpa.test.canonical.TestCanonicalMetaModel
[INFO] Running org.eclipse.persistence.jpa.test.criteria.TestCriteriaBuilder
[INFO] Running org.eclipse.persistence.jpa.test.mapping.TestUnidirectionalOneToMany
[INFO] Running org.eclipse.persistence.jpa.test.jpql.TestComplexJPQL
[INFO] Running org.eclipse.persistence.jpa.test.jpql.TestAggregateFunctions
[INFO] Running org.eclipse.persistence.jpa.test.modelgen.TestProcessor
[INFO] Running org.eclipse.persistence.jpa.test.server.TestJNDIConnector
[INFO] Running org.eclipse.persistence.jpa.test.server.TestTargetServerDetector
[INFO] Running org.eclipse.persistence.jpa.test.storedproc.TestDB2Platform
[INFO] Running org.eclipse.persistence.jpa.test.storedproc.TestDB2ZPlatform
[INFO] Running org.eclipse.persistence.jpa.test.sequence.TestSequenceStartAtNextValue
[INFO] Running org.eclipse.persistence.jpa.test.sequence.TestTableQualifier
[INFO] Running org.eclipse.persistence.jpa.test.property.TestParameterBinding
[INFO] Running org.eclipse.persistence.jpa.test.property.TestSQLCallDeferall
[INFO] Running org.eclipse.persistence.jpa.test.property.TestSQLCast
[INFO] Running org.eclipse.persistence.jpa.test.locking.TestTimestampVersionLocking
[INFO] Running org.eclipse.persistence.jpa.test.locking.TestPessimisticLocking
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestNVarChar
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestBasicPersistence
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestNullByteArrayEntry
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestSessionCustomizer
[INFO] Running org.eclipse.persistence.jpa.test.version.TestVersioning
[INFO] Running org.eclipse.persistence.jpa.test.concurrency.TestConcurrencyPersistence
[INFO] Running org.eclipse.persistence.jpa.test.lob.TestLobMerge
[INFO] Running org.eclipse.persistence.jpa.test.oraclefeatures.TestOracleLOBLocatorFeature
[INFO] Running org.eclipse.persistence.jpa.embeddable.TestNestedEmbeddable
[INFO] Running org.eclipse.persistence.config.TestPropertiesUtils
```

**Comment by dazey3** [comment]
@rfelcman Weird! Ill take a look and see what I can see

**Comment by dazey3** [comment]
@rfelcman Well, I can't reproduce this failure locally since the tests run in a completely different order for me, but Im guessing it might have something to do with `org.eclipse.persistence.jpa.test.basic.model.Employee`? I notice in this new order, TestQueryHints now runs BEFORE any of the other tests that also use `org.eclipse.persistence.jpa.test.basic.model.Employee`. I'm not quite sure why `DROP` fails the whole test, I thought that was safe, but I update my change so that `TestQueryHints` & `TestQueryProperties` use their own Employee table now. It should be convention to not share models around anyway.

**Comment by dazey3** [comment]
@rfelcman The more I look at this the less I understand why this is failing these tests. DROP/CREATE hasnt failed any tests in the past when DROP fails. I'm looking through the test output from all the JSE tests and I notice that many of the tests contain trace like:
```
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'COMPB' because it does not exist.
```
but they dont fail. This is very curious.

**Comment by rfelcman** [comment]
Yes for me it's odd too. I didn't have any trouble with this in Ant build too (locally, Jenkins, Travis). I'll try to simulate it by test suite to keep test order.

**Comment by dazey3** [comment]
@rfelcman Ok, I think I figure out the issue! I was able to reproduce the DROP issue and the issue was due to the ConnectionInvocationHandler implementation. The reason this InvocationHandler exists in the test is to listen for query execution and intercept the Statements. HOWEVER, the Handler is also intercepting the DROP query and re-throwing a InvocationTargetException!!! That was completely messing with the SQLException that was expected further up the stack. I added a catch and rethrow the cause() and it passes locally for me now.

**Comment by rfelcman** [comment]
Sorry, but I am still getting same error. There are errors in Ant build too (see Travis above) or my local stack trace:
```
TestQueryHints
testJDBCQueryTimeout

java.lang.reflect.UndeclaredThrowableException

javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:854)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:219)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:327)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:350)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
at org.eclipse.persistence.jpa.test.framework.EmfRunner.run(EmfRunner.java:43)
Caused by: java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy16.executeUpdate(Unknown Source)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2045)
at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:611)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:280)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:266)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeNoSelectCall(DatasourceCallQueryMechanism.java:310)
at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeNoSelect(DatasourceCallQueryMechanism.java:290)
at org.eclipse.persistence.queries.DataModifyQuery.executeDatabaseQuery(DataModifyQuery.java:88)
at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:915)
at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:3301)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1844)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1826)
at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1776)
at org.eclipse.persistence.internal.sessions.AbstractSession.priviledgedExecuteNonSelectingCall(AbstractSession.java:5096)
at org.eclipse.persistence.tools.schemaframework.DatabaseObjectDefinition.dropFromDatabase(DatabaseObjectDefinition.java:254)
at org.eclipse.persistence.tools.schemaframework.SchemaManager.dropObject(SchemaManager.java:555)
at org.eclipse.persistence.tools.schemaframework.TableCreator.dropTables(TableCreator.java:285)
at org.eclipse.persistence.tools.schemaframework.TableCreator.replaceTablesAndConstraints(TableCreator.java:359)
at org.eclipse.persistence.tools.schemaframework.TableCreator.replaceTables(TableCreator.java:351)
at org.eclipse.persistence.tools.schemaframework.SchemaManager.replaceDefaultTables(SchemaManager.java:1112)
at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.generateDefaultTables(EntityManagerFactoryProvider.java:114)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDLToDatabase(EntityManagerSetupImpl.java:4456)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDL(EntityManagerSetupImpl.java:4384)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDL(EntityManagerSetupImpl.java:4284)
at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:814)
Caused by: java.lang.reflect.InvocationTargetException
at org.eclipse.persistence.jpa.test.query.TestQueryHints$PreparedStatementInvocationHandler.invoke(TestQueryHints.java:338)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown table 'ecltests.QUERY_EMPLOYEE'
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
at com.mysql.jdbc.Util.getInstance(Util.java:408)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5116)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)


```

**Comment by rfelcman** [comment]
In Maven with MySQL:
```
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.128 s <<< FAILURE! - in org.eclipse.persistence.jpa.test.query.TestQueryHints
[ERROR] testJDBCQueryTimeout(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.059 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown table 'ecltests.QUERY_EMPLOYEE'
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testJDBCQueryTimeout(TestQueryHints.java:72)

[ERROR] testMultipleNamedQueryWithScrollableCursor(org.eclipse.persistence.jpa.test.query.TestQueryHints)  Time elapsed: 0.002 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ecltests.QUERY_EMPLOYEE' doesn't exist
	at org.eclipse.persistence.jpa.test.query.TestQueryHints.testMultipleNamedQueryWithScrollableCursor(TestQueryHints.java:231)
.....
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.058 s <<< FAILURE! - in org.eclipse.persistence.jpa.test.query.TestQueryProperties
[ERROR] testTimeoutUnitMinutes(org.eclipse.persistence.jpa.test.query.TestQueryProperties)  Time elapsed: 0.01 s  <<< ERROR!
javax.persistence.PersistenceException: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown table 'ecltests.QUERY_EMPLOYEE'
	at org.eclipse.persistence.jpa.test.query.TestQueryProperties.testTimeoutUnitMinutes(TestQueryProperties.java:131)
.....
.....
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   TestQueryHints.testJDBCQueryTimeout:72 » Persistence java.lang.reflect.Undecla...
[ERROR]   TestQueryHints.testMultipleNamedQueryWithScrollableCursor:231 » Persistence ja...
[ERROR]   TestQueryHints.testQueryTimeoutUnitMinutes:179 » Persistence java.lang.reflect...
[ERROR]   TestQueryHints.testQueryTimeoutUnitSeconds:132 » Persistence java.lang.reflect...
[ERROR]   TestQueryProperties.testTimeoutUnitDefault:77 » Persistence java.lang.reflect....
[ERROR]   TestQueryProperties.testTimeoutUnitMinutes:131 » Persistence java.lang.reflect...
[ERROR]   TestQueryProperties.testTimeoutUnitSeconds:106 » Persistence java.lang.reflect...
[INFO] 
[ERROR] Tests run: 113, Failures: 0, Errors: 7, Skipped: 0
```

**Comment by rfelcman** [comment]
and Maven (MySQL) execution order:
```
[INFO] Running org.eclipse.persistence.jpa.converter.TestAutoApplyConverter
[INFO] Running org.eclipse.persistence.jpa.collection.TestEmbeddableKey
[INFO] Running org.eclipse.persistence.jpa.collection.TestCollectionOperations
[INFO] Running org.eclipse.persistence.jpa.compositeid.TestCompositeId
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryHints
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryProperties
[INFO] Running org.eclipse.persistence.jpa.test.query.TestQueryCase
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDBPlatformDetector
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDDLGenLineTerminator
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestSchemaGen
[INFO] Running org.eclipse.persistence.jpa.test.ddl.TestDBPlatformHelper
[INFO] Running org.eclipse.persistence.jpa.test.canonical.TestCanonicalMetaModel
[INFO] Running org.eclipse.persistence.jpa.test.criteria.TestCriteriaBuilder
[INFO] Running org.eclipse.persistence.jpa.test.mapping.TestUnidirectionalOneToMany
[INFO] Running org.eclipse.persistence.jpa.test.jpql.TestComplexJPQL
[INFO] Running org.eclipse.persistence.jpa.test.jpql.TestAggregateFunctions
[INFO] Running org.eclipse.persistence.jpa.test.modelgen.TestProcessor
[INFO] Running org.eclipse.persistence.jpa.test.server.TestJNDIConnector
[INFO] Running org.eclipse.persistence.jpa.test.server.TestTargetServerDetector
[INFO] Running org.eclipse.persistence.jpa.test.storedproc.TestDB2Platform
[INFO] Running org.eclipse.persistence.jpa.test.storedproc.TestDB2ZPlatform
[INFO] Running org.eclipse.persistence.jpa.test.sequence.TestSequenceStartAtNextValue
[INFO] Running org.eclipse.persistence.jpa.test.sequence.TestTableQualifier
[INFO] Running org.eclipse.persistence.jpa.test.property.TestParameterBinding
[INFO] Running org.eclipse.persistence.jpa.test.property.TestSQLCallDeferall
[INFO] Running org.eclipse.persistence.jpa.test.property.TestSQLCast
[INFO] Running org.eclipse.persistence.jpa.test.locking.TestTimestampVersionLocking
[INFO] Running org.eclipse.persistence.jpa.test.locking.TestPessimisticLocking
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestNVarChar
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestBasicPersistence
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestNullByteArrayEntry
[INFO] Running org.eclipse.persistence.jpa.test.basic.TestSessionCustomizer
[INFO] Running org.eclipse.persistence.jpa.test.version.TestVersioning
[INFO] Running org.eclipse.persistence.jpa.test.concurrency.TestConcurrencyPersistence
[INFO] Running org.eclipse.persistence.jpa.test.lob.TestLobMerge
[INFO] Running org.eclipse.persistence.jpa.test.oraclefeatures.TestOracleLOBLocatorFeature
[INFO] Running org.eclipse.persistence.jpa.embeddable.TestNestedEmbeddable
[INFO] Running org.eclipse.persistence.config.TestPropertiesUtils
```

**Comment by dazey3** [comment]
@rfelcman OK! How about now? Based on the stack you supplied, I see the same `InvocationTargetException` is being thrown from the InvocationHandler. I think that failure is the same as the one I fixed before, but now coming from the other InvocationHandler. I added my fix to both InvocationHandlers now and it seems the test is passing now?

**Pull request merged**
