### PR TITLE
[master] Bug 567013: NullPointer check in weaved code

### PR DESCRIPTION
**Pull request by dazey3**
for #900

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by lukasj** [comment]
Isn't it callers responsibility to not call the setter with null value?

**Comment by dazey3** [comment]
@lukasj Do you have some documentation that states "null" values cannot be passed to this valueholder method? If it does get passed in it seems bad that we fail with a NullPointerException. Would it not be better to simply null check the value before attempting to use it? 

```java 
public void _persistence_set_foo_vh(WeavedAttributeValueHolderInterface paramWeavedAttributeValueHolderInterface) {
    this._persistence_foo_vh = paramWeavedAttributeValueHolderInterface;
    if (paramWeavedAttributeValueHolderInterface != null && paramWeavedAttributeValueHolderInterface.isInstantiated()) {
        Foo foo1 = _persistence_get_foo();
        Object object = paramWeavedAttributeValueHolderInterface.getValue();
        if (foo1 != object)
            _persistence_set_foo((Foo)object); 
        } else {
            this.user = null;
        } 
    }
}
```

**Comment by lukasj** [comment]
well, I could ask the same question the other way around: "Do you have documentation that states "null" values can be passed to this valueholder method?" Do you now what exactly one has to do to pass "null" there? Is it user who can do that? Is it some eclipselink code passing "null" there? A test would really help here...

**Comment by lukasj** [comment]
hmm, so when `DatabaseMapping.getAttributeValueFromObject()` is returning `{UnitOfWorkQueryValueHolder: not instantiated}` shouldn't `BasicIndirectionPolicy.getOriginalValueHolder()` return  `{UnitOfWorkQueryValueHolder: not instantiated}` too instead? Just asking...

**Review by lukasj — APPROVED** [review]
I would rather see the change on a different place but I can live with your solution

**Comment by dazey3** [comment]
@lukasj I really appreciate you looking into this issue. I also agreed with your assessment that without a test, this change was not satisfactory. After reinvestigating, I think the fix for [514486](https://github.com/eclipse-ee4j/eclipselink/issues/625) fixes the issue I was seeing in 2.6_WAS. Thank you.

**Pull request closed without merging**
