### PR TITLE
Bug 533272 - JPA NamedStoredProcedure call getOutputParameterValue with parameter name cause exception

### LINKED ISSUE #59: Bug 533272 - JPA NamedStoredProcedure call getOutputParameterValue with parameter name cause exception
Linked to [BZ #533272 ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=533272)

### PR DESCRIPTION
**Pull request by rieonke**
Fixed #59
Signed-off-by: Rieon Ke rieon@rieon.cn

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533272

**Comment by lukasj** [comment]
As soon as there will be a test for this

**Comment by dazey3** [comment]
Also update the header info

**Comment by rieonke** [comment]
@lukasj @dazey3 
So sorry that delayed for so long.
I was diagnosed with lymphoma a few months ago and still in hospital now.
I will add test as soon as possible

**Pull request merged**
