### PR TITLE
Issue #26: Make ValueHolderInterface api generic

### PR DESCRIPTION
**Pull request by vitgorbunov**
for #26

### CODE REVIEW

**Comment by vitgorbunov** [comment]
Do you mean in production code or including test as well?
Because there is at least 100 test classes that would need migration. Wouldn't it be better to migrate them one-by-one when needed (i.e. when they are being modified by some change)?

**Comment by lukasj** [comment]
> Do you mean in production code or including test as well?

Each of them would be awesome! But also a lot of work. I think we can stick with direct inheritance hierarchy (including method signatures) for the beginning, see ie IndirectCollection where parents and children will use generics but this class won't. 

As for 'one-by-one' approach - I prefer to avoid doing it this way as it sometimes makes code reviews as well as cherry-picking to different branches harder to do. But that's on case-by-case basis

**Comment by vitgorbunov** [comment]
Any comment on this please? Sorry for pushing, but I have some time to work on it this weekend and I'd like to get some feedback about current version before.

**Comment by vitgorbunov** [comment]
Hi @lukasj , 
It's been a while since latest feedback here. Could you take a look?

**Comment by dazey3** [comment]
@vitgorbunov I am fairly certain @lukasj will ask you to update the headers for each class. Take a look at other classes.

Example:
https://github.com/eclipse-ee4j/eclipselink/blob/ea5c77487819d44b821bee545651d85a8cd93535/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java#L32-L37

**Comment by vitgorbunov** [comment]
Thanks!

**Pull request merged**
