### PR TITLE
[master] Bug 537360: Update asm to version 6.2

### PR DESCRIPTION
**Pull request by Cousjava**
for #195

### CODE REVIEW

**Comment by Cousjava** [comment]
@lukasj What is a CQ?

I got the sources from http://search.maven.org/remotecontent?filepath=org/ow2/asm/asm/6.2/asm-6.2-sources.jar and the binary from http://search.maven.org/remotecontent?filepath=org/ow2/asm/asm/6.2/asm-6.2.jar

**Comment by lukasj** [comment]
CQ stands for Contribution Questionnaire - https://www.eclipse.org/projects/handbook/#ip-cq - only actual project committers can file that...

**Comment by Cousjava** [comment]
I've rebuilt asm with the debug mode turned on

**Comment by lukasj** [comment]
the bug 537313 is there for PDE which is completely different product from EclipseLink, so I filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=537360, related CQ 17020 has been already approved, so once the test build failure is resolved, we can merge this PR

**Comment by dazey3** [comment]
Hello! Will this be backported to 2.7? If so, I'd like to see this get in for 2.7.3 as well. Thanks!

**Comment by lukasj** [comment]
@dazey3 I'll backport it to 2.7 in a while...

**Pull request merged**
