### PR TITLE
[Master] Bug 579726: CriteriaBuilder neg() only returns Integer type, instead …

### PR DESCRIPTION
**Pull request by jgrassel**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579726

Signed-off-by: Joe Grassel <fyrewyld@gmail.com>

### CODE REVIEW

**Comment by jgrassel** [comment]
#run-libby-bot

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Hey can I get a review for this PR?  Thanks.

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
