### PR TITLE
[3.0] ASM version switch to 9.5 to be ready for JDK 21.

### PR DESCRIPTION
**Pull request by rfelcman**
As https://central.sonatype.com/artifact/org.eclipse.persistence/org.eclipse.persistence.asm/9.5.0 is released.

### CODE REVIEW

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by maffe** [comment]
Is there an estimate when this fix will be included in the artifacts available via Maven Central?

**Comment by rfelcman** [comment]
Are You strictly limited to 3.x line or it's possible use 4.x line like
https://github.com/eclipse-ee4j/eclipselink/releases/tag/4.0.2

**Comment by rfelcman** [comment]
Or https://github.com/eclipse-ee4j/eclipselink/releases/tag/3.0.4-RC1 will be available in Maven Central today.
I hope, that final version 3.0.4 on Wednesday.

**Comment by rfelcman** [comment]
See
https://github.com/eclipse-ee4j/eclipselink/releases/tag/3.0.4
https://repo1.maven.org/maven2/org/eclipse/persistence/eclipselink/3.0.4/
released today

**Pull request merged**
