### PR TITLE
[Master] Update Eclipselink to use Eclipselink*Visitor types

### PR DESCRIPTION
**Pull request by jgrassel**
Eclipselink*Visitor types have been added to the Eclipselink ASM project, which moves the use of the ASM# constants out of the Eclipselink project and into the Eclipselink ASM project.  This should make it easier to avoid missing updating all of the constants when moving up to new major versions of ASM.

### CODE REVIEW

**Comment by jgrassel** [comment]
(Yeah, figured it'd fail without ecl-asm-9.1.1 published.  There a way to kick off the checks again once it's published?)

**Comment by lukasj** [comment]
the pr check build should not fail, it is set up to use artifacts from staging repository

**Comment by jgrassel** [comment]
Is this stuck?  It looks like it can't find an executor:
```
Still waiting to schedule task
Waiting for next available executor on ‘el-master-agent-pod-4np2l-qjthv’
```

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by dazey3** [comment]
@lukasj @jgrassel Does this build? Have we published `org.eclipse.persistence:org.eclipse.persistence.asm:9.1.1` yet?

**Comment by lukasj** [comment]
Yes, same (or similar) change in 3.0/2.7 needs to be done. Merge or work on those other PRs does not need to wait `-Pstaging` does the trick for the build to pass for now.

**Pull request merged**
