### PR TITLE
[2.7] Fix for ReportQuery not fetching relationships with BatchFetch.IN

### PR DESCRIPTION
**Pull request by Sheikah45**
Backport of #2303

### CODE REVIEW

**Comment by Sheikah45** [comment]
I tried to add the test classes in but wasn't sure where the persistence.xml was supposed to go

**Review by rfelcman — COMMENTED** [review]
`persistence.xml` should be under new folder `eclipselink-batchfetch-model`
in
`https://github.com/eclipse-ee4j/eclipselink/tree/2.7/jpa/eclipselink.jpa.test/resource`
NOTE: Don't forget if there are some `jakarta.persistence` properties to rename into `javax.persistence` and XML Schema should be same as
https://github.com/eclipse-ee4j/eclipselink/blob/2.7/jpa/eclipselink.jpa.test/resource/eclipselink-beanvalidation-model/persistence.xml
`<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence persistence_2_0.xsd" version="2.0">`

Plus changes in 
https://github.com/eclipse-ee4j/eclipselink/blob/2.7/jpa/eclipselink.jpa.test/antbuild.xml
https://github.com/eclipse-ee4j/eclipselink/blob/2.7/jpa/eclipselink.jpa.test/antbuild.properties
but just modify java part plus add `persistence.xml` I'll handle Ant build scripts.

**Comment by rfelcman** [comment]
See https://github.com/Sheikah45/eclipselink/pull/2

**Review by rfelcman — APPROVED** [review]
LGTM

**Pull request merged**
