### PR TITLE
Set default value of JoinFetch annotation to INNER and BatchFetch annotation to JOIN

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Review by lukasj — CHANGES_REQUESTED** [review]
ECA check failed

**Comment by arjantijms** [comment]
@lukasj the check seems to pass now

**Comment by lukasj** [comment]
@arjantijms there is the `re-request review` button/feature which one can use to get attention. Usually more helpful

**Comment by arjantijms** [comment]
> Usually more helpful

Good one, I'll look at it next time. Thanks!

**Pull request merged**
