### PR TITLE
[2.7] Update Eclipselink bundled ASM to version 7.1 for JDK 13 support.

### PR DESCRIPTION
**Pull request by jgrassel**
Signed-off-by: Joe Grassel <fyrewyld@gmail.com>

Updating the bundled ASM in Eclipselink to 7.1 to support JDK 13.

### CODE REVIEW

**Comment by andreak** [comment]
Any ETA for release 2.7.5 for JDK-13 support?

**Comment by rfelcman** [comment]
I hope, that during next few days. At least if You want make some tests 2.7.5-RC1 is out.
See
https://search.maven.org/search?q=g:org.eclipse.persistence%20AND%20v:2.7.5-RC1
https://www.eclipse.org/eclipselink/downloads/milestones.php

**Comment by andreak** [comment]
Great!
I'll test 2.7.5-RC1

**Comment by andreak** [comment]
I'm getting:
```
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [/path/to/SomeClass.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 57
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:57)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
```
But I guess that's a problem with AspectJ? (I'm using Spring with AspectJ for load-time-weaving)

**Comment by lukasj** [comment]
`org.springframework...` why do you think this is eclipselink related?

**Comment by andreak** [comment]
I'm not sure if they are "competing" with some ASM-libs, maybe not...

**Comment by lukasj** [comment]
could it be just the fact that your version of spring does not support java 13 like it is said ie here: https://stackoverflow.com/questions/57299672/how-to-fix-unsupported-class-file-major-version-57-in-maven-for-java-13-and-spri ?

**Comment by andreak** [comment]
Most likely:-)

**Pull request merged**
