### PR TITLE
[master] Bug #542491: 'eclipselink.jdbc.force-bind-parameters' property fails …

### PR DESCRIPTION
**Pull request by dazey3**
for #492

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
@lukasj Who should I contact to fix Travis?

**Comment by lukasj** [comment]
@dazey3 .travis.yml file in the root of the repo + travis doc. This is probably way to fix it: https://docs.travis-ci.com/user/languages/java/#updating-oracle-jdk-8-to-a-recent-release

**Comment by dazey3** [comment]
@lukasj Ya, I don't think that is going to help. It doesnt look like a configuration issue to me. I think someone with command line access to Travis needs to fix it.

```
The following packages have unmet dependencies:
 mysql-client : Depends: mysql-client-5.5 but it is not going to be installed
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Is mysql 5.5 conflicting with another version already installed? 

```
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157  
```
Maybe there is some issue with the public key?

**Comment by dazey3** [comment]
@lukasj Ok, lots of digging later, I think I figured out what the issue is: https://forums.mysql.com/read.php?11,677237,677268#msg-677268

**Comment by dazey3** [comment]
@lukasj Now that the travis testing has been fixed, can I get a review for this change? Thanks in advance!

**Pull request merged**
