### PR TITLE
Bug25238004

### PR DESCRIPTION
**Pull request by sureshbn**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=25238004

**Comment by dazey3** [comment]
Could you please squash your commits together (git rebase master -i) and re-push to your fork? It just makes things look a lot cleaner (in case who ever merges this forgets to "squash and merge")

**Comment by dazey3** [comment]
What is this pull request meant to fix? Is this related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=533724, which has already been closed by #74

**Comment by lukasj** [comment]
this should be reworked, if needed

**Pull request closed without merging**
