### PR TITLE
update dependencies, build plugins

### PR DESCRIPTION
**Pull request by lukasj**
and move travis from jdk14 to jdk15

### CODE REVIEW

**Review by rfelcman — COMMENTED** [review]
It seems, that there is compilation error on JDK 15 in `eclipselink.dbws.builder.test.oracle` module. See Travis-CI logs.

**Review by rfelcman — APPROVED** [review]
LGTM

**Comment by jgrassel** [comment]
Which CQ was used to get asm 9 approved for eclipselink?  I'm interested in backporting asm 9 to 2.7 and 2.6_WAS.

**Comment by rfelcman** [comment]
> Which CQ was used to get asm 9 approved for eclipselink? I'm interested in backporting asm 9 to 2.7 and 2.6_WAS.

Sorry it seems, the we forget to create a new one. I used Your 22750. I attached it to #936 .

**Pull request merged**
