### PR TITLE
Update javadoc

### PR DESCRIPTION
**Pull request by jbescos**
Relates to issue #1138

### CODE REVIEW

**Review by lukasj — COMMENTED** [review]
foundation/eclipselink.core.test/src/it/resources/org/eclipse/persistence/testing/models/workbenchintegration/Employee_utf16.xml and sdo/org.eclipse.persistence.sdo/src/test/resources/org/eclipse/persistence/testing/sdo/helper/jaxbhelper/xmlhelper/GlobalElement_UTF16.xml must remain valid UTF-16 files.

**Comment by lukasj** [comment]
JDK 11 works fine but:

```
ljungman-mac:eclipselink lukas$ java -version
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+27-2476)
OpenJDK 64-Bit Server VM (build 17-ea+27-2476, mixed mode, sharing)
ljungman-mac:eclipselink lukas$ mvn -U -C clean install -Poss-release
...
[ERROR] 59 errors
[ERROR] 100 warnings
[ERROR] 
[ERROR] Command line was: /Users/lukas/java/jdk-17.jdk/Contents/Home/bin/javadoc -J-Xms2048m @options @packages @argfile
...
```

**Comment by jbescos** [comment]
I'm postponing this, it requires still much work.

**Comment by jbescos** [comment]
I have done some more updates, and now it works to me when I execute:
mvn -U -C clean install -Poss-release
openjdk 17-ea 2021-09-14

This files I don't know what happened with the copyright plugin. I have modified the copyright without it:
`foundation/eclipselink.core.test/src/it/resources/org/eclipse/persistence/testing/models/workbenchintegration/Employee_utf16.xml and sdo/org.eclipse.persistence.sdo/src/test/resources/org/eclipse/persistence/testing/sdo/helper/jaxbhelper/xmlhelper/GlobalElement_UTF16.xml must remain valid UTF-16 files.`

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
