### PR TITLE
Bug 534812 - HIERARCHY_REQUEST_ERR marshalling a CDATA-containing XmlAnyElement to a Node result

### PR DESCRIPTION
**Pull request by rfelcman**
Bug 534812 - HIERARCHY_REQUEST_ERR marshalling a CDATA-containing XmlAnyElement to a Node result

Bug fix in org.eclipse.persitence.NodeRecord.characters().
CDATA handling implementation in org.eclipse.peristence.platform.xml.SAXDocumentBuilder (see MOXy bug 355143).
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=534812

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=534812

**Comment by rfelcman** [comment]
Hello Peter,

     Sorry but project owner is out of office this week. I hope, the we 
will merge this fix into 2.7.2 branch too. I think, the 2.7.2 version 
will be released next week.

                                                             Thank You
                                                             Radek Felcman

Peter wrote:

**Comment by petergeneric** [comment]
Hi @rfelcman is it possible to get a 2.7.2 release with this fix? I don't see one in central

**Comment by rfelcman** [comment]
Hello,

     it will be part of 2.7.2 release
     see pull request
         https://github.com/eclipse-ee4j/eclipselink/pull/110
     and relase notes for 2.7.2 (MOXy part)
https://projects.eclipse.org/projects/ee4j.eclipselink/releases/2.7.2/bugs

     but version 2.7.2 isn't released yet.

                                                         Radek Felcman

Peter wrote:

**Pull request merged**
