### PR TITLE
Enable FK creation for SAP HANA

### PR DESCRIPTION
**Pull request by alexanderparr**
Signed-off-by: Alexander Parr <alexander.parr@projektraum36.de>

### CODE REVIEW

**Comment by alexanderparr** [comment]
Update of PR #491 

When using HANAPlatform as target database, we noticed that foreign key constraints are not created on HANA DB. This has been discussed here as well:
https://answers.sap.com/questions/601226/jpa-works-to-create-database-tables-locally-but-no.html

As times of missing FK support on HANA are over, you might consider merge my pull request, to support FK creation?

**Comment by dazey3** [comment]
@alexanderparr Thanks for going through the approval process! For future reference, you can rerun any of the pull request checks by going to "Details". It saves time rather than creating a whole new pull request.

**Comment by alexanderparr** [comment]
@dazey3 thanks for the hint. I saw that button and tried it out but I missed the signed-off statement in my git message also. In addition, I do not know how to rebase my pull request branch onto the latest version of the forked branch and how to change my commit message :/ Sorry - I'm new to GitHub

**Comment by dazey3** [comment]
@alexanderparr NP! Iv definitely been there :) 

We have a wiki page that helps to lay out some steps to creating a pull request if you aren't familiar and it includes the necessary '-signoff' argument: https://github.com/eclipse-ee4j/eclipselink/wiki/Creating-a-Pull-Request

Another useful command that I use:
```
git rebase <branch> -i
```
This command opens up an editor where you can edit your commit messages or squash commits together into one!

**Comment by dazey3** [comment]
Interesting! Kind of an aside, but I was looking at the HANA doc and it says:
```
LOB columns cannot appear in SELECT DISTINCT clauses
```
which probably means HANAPlatform should override `DatabasePlatform.isLobCompatibleWithDistinct()` at some point...

**Comment by dazey3** [comment]
hmmmmmm, it seems there is a bug in EclipseLink's platform detection for HANA... 

Some log I took while playing around with a HANA DB:
```
DatabaseSessionImpl.setOrDetectDatasource.vendorNameAndVersion: HDB22.00.040.00.1553674765
DatabaseSessionImpl.setOrDetectDatasource.driverName: HDB
DatabaseSessionImpl.setOrDetectDatasource.platformName: org.eclipse.persistence.platform.database.DB2Platform
```

Our regex parser sees "DB2" in "HDB22.00.040.00.1553674765" and thinks it's DB2Platform... *facepalm*

I need to fix this...

**Comment by lukasj** [comment]
@alexanderparr can you do the PR also to 2.7 branch, please? Thanks!

**Pull request merged**
