### PR TITLE
[master] Bug 578262: Bulk update queries reuse the same version locking value

### PR DESCRIPTION
**Pull request by dazey3**
for #1398

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
The fix for this issue changes the query behavior for bulk updates with timestamp version locking values

Current:
```
****CREATING QUERY****
Execute query ValueReadQuery(sql="SELECT NOW()")
****EXECUTING QUERY****
Execute query UpdateAllQuery(referenceClass=EcallRegistration sql="UPDATE ECALLREGISTRATION SET ECALLAVAILABLEFLAG = ?, sys_update_timestamp = ? WHERE (PK = ?)")
```
Currently, EclipseLink executes two separate queries: one during query prepare that gets a TimeStamp value from the database and one during query execute that uses the value obtained during create/prepare

Changed:
```
****CREATING QUERY****
****EXECUTING QUERY****
Execute query UpdateAllQuery(referenceClass=EcallRegistration sql="UPDATE ECALLREGISTRATION SET ECALLAVAILABLEFLAG = ?, sys_update_timestamp = CURRENT_TIMESTAMP WHERE (PK = ?)")
```
With this change, create/prepare for UpdateAllQuery no longer executes a separate query to obtain timestamp values. Instead, create/prepare now uses CURRENT_TIMESTAMP(`ExpressionOperator.Today`), which is defined in the JPA spec and already supported by existing platforms, to add the platform specific CURRENT_TIMESTAMP function to the query. This should be fine for bulk updates as the specification doesn't expect updates (and EclipseLink doesnt currently do so) as stated in section 4.10

**Review by lukasj — COMMENTED** [review]
can this be rebased on master, please?

**Comment by dazey3** [comment]
Rebased and tests rerunning. I assume this is so that the new tests delivered under https://github.com/eclipse-ee4j/eclipselink/pull/1403 are included?

**Comment by lukasj** [comment]
> I assume this is so that the new tests delivered under #1403 are included?

it's about getting rid of unrelated changes to make the code easier to review

**Review by lukasj — APPROVED** [review]
LGTM

**Pull request merged**
