### PR TITLE
[3.0] Bug 1343: Remove getStackTrace to fix throughput degredation

### PR DESCRIPTION
**Pull request by dazey3**
for #1343

Signed-off-by: Joshua Dettinger <joshuad@us.ibm.com>
Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
@rfelcman Does this PR look ok to merge?

**Comment by rfelcman** [comment]
Sorry, but "continuous-integration/jenkins/pr-merge" prints some test errors see details https://ci.eclipse.org/eclipselink/job/eclipselink-pull-request-verifier/job/PR-1345/ . I executed this PR verification job again https://ci.eclipse.org/eclipselink/job/eclipselink-pull-request-verifier/job/PR-1345/2/ but with the same results.
You can compare it with
https://ci.eclipse.org/eclipselink/job/eclipselink-pull-request-verifier/job/3.0/
or
https://ci.eclipse.org/eclipselink/job/eclipselink-nightly-3.0/

**Comment by dazey3** [comment]
@rfelcman I'm not sure why this is failing on 3.0 but not 2.7 or master? This change is really small and functionally the same thing. I have a hard time seeing why there would be failures based on THIS commit.

**Comment by dazey3** [comment]
@rfelcman 

The 4 test failures are in WDF and I have absolutely no knowledge of that code:
```
Test: org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestFlush(test-jpa-wdf).testRelationshipToNew
Error Details           flush succeeded although there is a relation to an unmanaged

Test: org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference(test-jpa-wdf).testPersist
Error Details           persisting a hollow entity succeeded (should fail)

Test: org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference(test-jpa-wdf).testRemoveNonExisting
Error Details           PersistenceException not thrown as expected

Test: org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference(test-jpa-wdf).testNegativ
Error Details           no EntityNotFoundException
```

They appear to be all negative tests expecting failures that didn't happen.

`org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference.testPersist()`

So this test failed because it expected the persist/flush to fail. Why? The test seems like the entity should be persisted just fine. The test is not documented very well on what it is testing. What is a "a hollow entity" a reference to?

**Comment by dazey3** [comment]
Perhaps these tests expect to be run in a specific order and have skated by in the past on that? But now they are running in an unexpected order? Looking at some of them, comments appear to indicate the tests do not expect some values to be in the database:

org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference.testRemoveNonExisting()
```java
    Employee emp = em.getReference(Employee.class, Integer.valueOf(99)); // versioning, entity does not exist
```

But if the entity DOES exist, then the test doesn't fail and other tests ARE persisting the same ID:
org.eclipse.persistence.testing.tests.wdf.jpa1.entitymanager.TestGetReference.testPersist():
```java
Employee emp = null;
            boolean operationFailed = false;
            env.beginTransaction(em);
            try {
                emp = em.getReference(Employee.class, Integer.valueOf(99));
            } catch (EntityNotFoundException e) {
                // $JL-EXC$ expected behavior
                operationFailed = true;
            }
            env.rollbackTransactionAndClear(em);

            if (emp != null) {
                env.beginTransaction(em);
                try {
                    em.persist(emp);
                    em.flush();
                } catch (PersistenceException e) {
                    // $JL-EXC$ expected behavior
                    operationFailed = true;
                }
                env.rollbackTransactionAndClear(em);
                verify(operationFailed, "persisting a hollow entity succeeded (should fail)");
            }
```
It seems like if `testPersist()` doesnt fail, then `testRemoveNonExisting()` has to fail. Bad testing.

**Comment by dazey3** [comment]
In any case, I don't think any of these test failures are related to this PR and should be overlooked. I would like to get this change merged so that 3.0 can match 2.7 and master in ConcurrencyManager

**Review by rfelcman — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
> In any case, I don't think any of these test failures are related to this PR and should be overlooked

that happens to me from time to time and I go ahead and fix those failures - setting specific order is not that difficult change to make. What have you done to make sure failures you see will be addressed?

**Pull request merged**
