### PR TITLE
[2.6] Bug 391279: Add support for Unidirectional OneToMany with non-nullable value

### PR DESCRIPTION
**Pull request by lukasj**
backport of #233 to 2.6

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>
Reviewed-by: Lukas Jungmann <lukas.jungmann@oracle.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=391279

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=391279

**Comment by dazey3** [comment]
Oh, I wasn't sure if we are still backporting to 2.6... are we planning on cutting a new 2.6 release at some point?

**Comment by lukasj** [comment]
Yes, likely right after this PR. But generally speaking, only really important fixes should go into 2.6 (what gets to 2.6_WAS should get into 2.6 as well and vice-versa)

**Comment by dazey3** [comment]
I know we have a test bucket that was waiting for 2.6.6 (specifically Java support from [Bug 525854](http://git.eclipse.org/c/eclipselink/eclipselink.runtime.git/commit/?h=2.6&id=2d430ab4dcfd894ad3abe52992487d5fc5a1802d)

**Comment by lukasj** [comment]
Let's reuse this one

**Pull request merged**
